# Generated by Django 3.2 on 2023-06-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='image'),
        ),
    ]
