# Generated by Django 3.2 on 2023-05-20 09:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('property_status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('rented', 'Rented')], max_length=30)),
                ('property_type', models.CharField(choices=[('condo', 'Condo'), ('studio', 'Studio'), ('house', 'House'), ('plot', 'Plot'), ('mension', 'Mension'), ('shop', 'Shop'), ('hotel', 'Hotel'), ('warehouse', 'Warehouse')], default='for_rent', max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=5)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('types', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
