# Generated by Django 3.2 on 2023-06-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=7.8942, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=-72.5039, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
    ]
