# Generated by Django 3.2 on 2023-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20230603_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
    ]
