# Generated by Django 3.2 on 2023-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.AddField(
            model_name='property',
            name='exterior_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='interior_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=255),
        ),
    ]
