# Generated by Django 3.2 on 2023-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20230608_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='size_unit',
            field=models.CharField(choices=[('meter', 'm^2'), ('hectares', 'hectáreas')], default='meter', max_length=10),
        ),
    ]
