# Generated by Django 3.2 on 2023-06-20 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=10),
        ),
    ]
