# Generated by Django 3.2 on 2023-06-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='exterior_size',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='interior_size',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('rented', 'Rented'), ('idle', 'Idle')], default='idle', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('meter', 'm^2'), ('hectares', 'hectáreas')], default='meter', max_length=10, null=True),
        ),
    ]
