# Generated by Django 3.2 on 2023-07-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20230627_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='department',
        ),
    ]
